#!/usr/bin/env python3
"""
Plain-text exports — the free take-it-with-you surfaces.

export_text renders the whole session as one readable .txt (idea, straight read, graded
receipts, the plan so far, the board's take); handoff_prompt renders an LLM-ingestion prompt so
the operator can continue in ANY model from exactly where they left off; slug names the
downloads. Pure functions of the session dict; raw export stays free by design (ownership is
the wedge — sell the polish, never the exit).
"""

from __future__ import annotations

import re

from app import planner


def export_text(s: dict) -> str:
    """Everything the operator has generated so far, as ONE plain-text dump: the idea + offer summary,
    the straight read, the plan part by part, the annotated graded research, and the board's takes.
    Minimal formatting on purpose — it's a get-your-data-out file, available at any point, always free."""
    out: list[str] = []
    W = out.append
    BAR = "=" * 64
    R = s.get("research") or {}
    prose = R.get("prose") or {}
    v = s.get("vetting") or {}
    sh = s.get("shaped") or {}
    W("FILG — YOUR BUSINESS PLAN, SO FAR")
    W("Built with FILG. Every number is graded by a source-credibility gate: vendor-marketing stats are")
    W("labeled, not laundered. This is your raw export, it's always free.")
    W("")
    W(BAR); W("THE IDEA"); W(BAR)
    W((s.get("idea") or "").strip())
    if prose.get("title"):
        W(""); W("Offer: " + prose["title"])
    if prose.get("offer"):
        W("What you'd sell: " + prose["offer"])
    if prose.get("gtm"):
        W("How you'd sell it: " + prose["gtm"])
    if v.get("verdict"):
        shape = ("  ·  shape: " + v["model_type"].replace("-", " ")) if v.get("model_type") else ""
        W("Verdict: " + v["verdict"].upper() + shape)
    W("")
    if sh or v:
        W(BAR); W("THE STRAIGHT READ"); W(BAR)
        if sh.get("thesis"):
            W("Focus: " + sh["thesis"])
        if sh.get("founder_edge"):
            W("Your edge: " + sh["founder_edge"])
        if v.get("reason"):
            W(v["reason"])
        if v.get("biggest_risk"):
            W("Biggest risk: " + v["biggest_risk"])
        if v.get("first_test"):
            W("Cheapest first test: " + v["first_test"])
        for a in (v.get("premortem") or []):
            why = ("  (" + a["why"] + ")") if a.get("why") else ""
            W("  - [" + str(a.get("status", "")) + "] " + str(a.get("assumption", "")) + why)
        W("")
    files = s.get("files") or {}
    if files:
        W(BAR); W("THE PLAN, PART BY PART"); W(BAR)
        for sec in planner.SECTIONS:
            if sec["file"] in files:
                W(""); W("## " + sec["title"] + " — " + sec.get("sub", ""))
                W((files[sec["file"]] or "").strip())
        W("")
    rows = R.get("rows") or []
    if rows:
        W(BAR); W("THE RESEARCH, GRADED"); W(BAR)
        W("Each claim is marked CITED (passed the gate) or VENDOR/UNVERIFIED (treat with care).")
        for r in rows:
            mark = "CITED" if r.get("mark") == "ok" else "VENDOR/UNVERIFIED"
            W(""); W("[" + mark + "] " + (r.get("text") or ""))
            meta = [x for x in (r.get("url"), r.get("note"),
                                ("as of " + str(r["as_of"])) if r.get("as_of") else None) if x]
            if meta:
                W("    " + "  ·  ".join(meta))
        W("")
    board = s.get("board") or []
    if board:
        W(BAR); W("YOUR BOARD'S TAKE (composite advisors, not real people)"); W(BAR)
        for rev in board:
            W(""); W("On “" + (rev.get("title") or "") + "”:")
            sk = rev.get("skeptic") or {}
            if sk.get("rationale"):
                W("  Skeptic (" + str(sk.get("verdict", "")) + "): " + sk["rationale"])
            for d in (rev.get("directors") or []):
                W("  " + (d.get("first") or d.get("name") or "Director") + ": " + (d.get("take") or ""))
            if rev.get("verdict"):
                W("  Board takeaway: " + rev["verdict"])
        W("")
    W(BAR)
    W("Generated by FILG · fuckitletsgo.ai · your raw export is always free.")
    return "\n".join(out)


def handoff_prompt(s: dict) -> str:
    """An LLM-ingestion prompt so the operator can paste their work into ANY model and pick up exactly
    where they left off: the idea + straight read, the plan parts already written, the part they're on
    now, the graded research WITH source links, and the board's notes — then a continue-from-here task.
    We never include sections ahead of where they are."""
    out: list[str] = []
    W = out.append
    R = s.get("research") or {}
    prose = R.get("prose") or {}
    v = s.get("vetting") or {}
    sh = s.get("shaped") or {}
    files = s.get("files") or {}
    prop = s.get("proposal") or {}
    W("You are a pragmatic business-planning partner for a solo operator. They started building a plan "
      "in another tool and want you to continue from exactly where they left off. Everything generated "
      "so far is below: the idea, the honest read on it, the plan parts already written, the part they "
      "are on now, the graded research (with source links), and their board's notes.")
    W("")
    W("Rules: keep the same buyer, offer, price, and numbers already chosen; stay concise; build on the "
      "parts already written instead of redoing them; treat any source marked VENDOR/UNVERIFIED as "
      "unproven; do not invent statistics.")
    W("")
    W("=== THE IDEA ===")
    W((s.get("idea") or "").strip())
    if prose.get("title"):
        W("Offer: " + prose["title"])
    if prose.get("offer"):
        W("What they'd sell: " + prose["offer"])
    if prose.get("gtm"):
        W("How they'd sell it: " + prose["gtm"])
    if v.get("verdict"):
        W("Verdict so far: " + v["verdict"].upper()
          + (("  ·  shape: " + v["model_type"].replace("-", " ")) if v.get("model_type") else ""))
    if sh.get("founder_edge"):
        W("Founder's edge: " + sh["founder_edge"])
    if v.get("biggest_risk"):
        W("Biggest risk: " + v["biggest_risk"])
    W("")
    if files:
        W("=== THE PLAN SO FAR (already written — build on these, don't repeat) ===")
        for sec in planner.SECTIONS:
            if sec["file"] in files:
                W(""); W("## " + sec["title"]); W((files[sec["file"]] or "").strip())
        W("")
    if prop.get("draft") and not s.get("done"):
        W("=== THE PART THEY'RE ON NOW (a draft, not yet locked) ===")
        W("## " + (prop.get("title") or ""))
        W((prop.get("draft") or "").strip())
        W("")
    rows = R.get("rows") or []
    if rows:
        W("=== GRADED RESEARCH (with source links) ===")
        for r in rows:
            mark = "CITED" if r.get("mark") == "ok" else "VENDOR/UNVERIFIED"
            url = ("  <" + r["url"] + ">") if r.get("url") else ""
            W("- [" + mark + "] " + (r.get("text") or "") + url)
        W("")
    board = s.get("board") or []
    if board:
        W("=== THE BOARD'S NOTES (composite advisors) ===")
        for rev in board:
            sk = rev.get("skeptic") or {}
            tail = ("  | skeptic (" + str(sk.get("verdict", "")) + "): " + sk["rationale"]) if sk.get("rationale") else ""
            W("- on “" + (rev.get("title") or "") + "”: " + (rev.get("verdict") or "") + tail)
        W("")
    W("=== YOUR TASK ===")
    if s.get("done"):
        W("The plan is complete. Pressure-test it, then help them sharpen the weakest part and plan the "
          "first 30 days of execution.")
    else:
        nxt = ""
        st = s.get("step")
        if isinstance(st, int) and 0 <= st + 1 < len(planner.SECTIONS):
            nxt = " The next part to write is “" + planner.SECTIONS[st + 1]["title"] + "”."
        W("Continue the plan from the part they're on now, keeping it tight and consistent with "
          "everything above." + nxt)
    return "\n".join(out)


def slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "business-plan").lower()).strip("-")
    return (s or "business-plan")[:50]
